name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '*/5 * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'arminmiau'
          git config --global user.email 'arminmiau@users.noreply.github.com'
          git pull --unshallow 
          git remote add upstream https://github.com/example/test.git
          git fetch upstream
          git checkout -b feature/x origin/feature/x
          git merge --no-edit upstream/feature/x
          git push origin feature/x
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
